* Basic Sweet Recipe
  - combine 1.25 cups bold(water) , 2.5tsp bold(yeast), and 1TB bold(sugar) to bowl
  - add 3cups bold(bread flour), 1/3 cup bold(vital wheat gluten) (adds chew), .5 cup bold(sourdough start)  and mix till just combined.
  - add in .5 cup of bold(stuff)  where stuff can be blueberries, cranberries, nuts..
  - let dough rest for 7min (this is so the flour, which can be dry, can absorb some of the water.)
  - Kneed for 5 minutes in the mixer on med-low speed.
  - add 1TB bold(salt)  (you don't add to the beginning as the salt can interfere with gluten structure.)
  -  Kneed for an additional 5 minutes.
  - Turn dough out on  counter and flatten, if you want a cinnamon swirl, sprinkle bold(cinnamon) in six lines across the dough and fold in half and kneed briefly.
  - Place dough in a bold(greased bowl), cover and let double in a warm place.  If you cover the bowl with clear wrap, you can use a marker to draw a circle around the dough to show how much it's growing.
  - Punch down and divide into 12 4oz pieces, let rest for about 5 min.
  - shape pieces into balls, roll out into strips, and then wrap the strip around your hand and close it forming a ring.
  - place on flour lined parchment, or slipat, and proof for 15min.
  - combine .25cups bold(molasses) with 3qts bold(water) and bring to a simmer.
  - place bagels into water for 1 min, flip 1 min, and then place on sheetpan sprinkled with cornmeal.
  - bake bagels at 375F for 20min.

* Variations
  - Cranberry Orange Walnut : .5 cup walnut pieces, .5 cup dried cranberries, orange zest
  - Blueberry: 1 cup dried blueberries, lemon zest
